### ISSUE TITLE
Same cipher every day

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#100]
**Describe the bug**
Every day uses the same cipher.

**To Reproduce**

1. Solve today's cryptogram
2. Open a new window and click on the calendar and select yesterday's cryptogram.
3.Solve yesterday's cryptogram
4. Compare the alphabets of both cryptograms.  They will be the same.

**Expected behavior**
Each day should have a distinct random key.

**Screenshots**
![Screen Shot 2024-03-08 at 11 07 33 AM](https://github.com/cesine/fantastic-lamp/assets/
![Screen Shot 2024-03-07 at 4 52 54 PM](https://github.com/cesine/fantastic-lamp/assets/1167732/ed6fae36-f6e1-4de7-a0e6-e6ca9fabac35)
1167732/57f67ada-338e-4085-a4e2-c3eec605efd9)

![Screen Shot 2024-03-08 at 11 20 25 AM](https://github.com/cesine/fantastic-lamp/assets/1167732/d70a1f81-0065-4977-bdb7-da2d1a6365a5)

Note that in two different cryptograms "ZOO" = "ALL"

**Comment by cesine** [comment]
Thanks for finding this! i can see the reason is that hte seededRandom always returns the same value and just causes the cipher to be inverse sorted 

<img width="1995" alt="Screenshot 2024-03-08 at 3 45 36 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/aa118832-889c-491f-b5f0-cfbdec7574ef">
